### ISSUE TITLE
The pre-trained model is crashed

### ISSUE THREAD

**Issue by fanq15** [marvis/pytorch-mobilenet#5]
The pre-trained model can't be unzipped correctly.

**Comment by marvis** [comment]
can you give more details?

**Comment by fanq15** [comment]
When I load the model, it arise a bug:
```
Traceback (most recent call last):
  File "finetune.py", line 228, in <module>
    model_ft.load_state_dict(checkpoint['state_dict'])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 332, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.model.0.0.weight" in state_dict'
```

**Comment by fanq15** [comment]
I solved it. Thanks!
`https://stackoverflow.com/questions/44230907/keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict`
